# Configurations for general of video and bio-signals of egoPPG dataset

# General parameters
participants: ['005', '006', '007', '008', '009', '010', '011', '012', '013', '014', '015', '016', '017',
               '018', '019', '021', '022', '023', '024', '025', '026', '027', '028', '029', '030', '031', '032',
               '033', '034', '035', '036', '037', '038', '039', '040', '042', '043', '044', '045', '046']
fs_all: {'et': 90, 'rgb': 10, 'imu_right': 1000, 'ecg': 1024, 'eda': 256, 'ppg_nose': 128, 'rr': 400, 'gaze': 90,
         'pupils': 90, 'intensity': 90, 'lbptop': 9}

# Define personality and emotions
affect_domains: ["Arousal", "Valence", "Dominance"]
personality_domains: ["Extraversion", "Agreeableness", "Conscientiousness", "Negative Emotionality",
                      "Open-Mindedness"]
emotion_domains: ['Amused', 'Content', 'Excited', 'Awe', 'Neutral', 'Fear', 'Sad', 'Disgust', 'Anger']

pupils_side_to_use: {
  '009': 1,
  '017': 0,
  '018': 1,
  '019': 1,
  '025': 1,
  '037': 1,
  '039': 1,
  '044': 0,
  '045': 0
}

sensors_to_exclude : {
  '010': ['pupils'],
  '032': ['pupils'],
  '039': ['pupils'],
  '046': ['pupils']
}

sensors_missing : {
  '004': ["eda"]
}